name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build site
      run: npm run build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        
    # For Squarespace deployment, you typically need to:
    # 1. Build the static files (done above)
    # 2. Upload to a CDN or hosting service
    # 3. Update Squarespace custom code/embed blocks
    # 
    # Since Squarespace doesn't support direct static site deployment,
    # consider these alternatives:
    # - Host on GitHub Pages and embed via iframe
    # - Use a CDN like Netlify/Vercel and redirect from Squarespace
    # - Manually copy built files to Squarespace code blocks
    
  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: ./dist
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4